language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
notifications:
  email:
    on_success: never
    on_failure: always