language: java
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8
notifications:
  email:
    on_success: never
    on_failure: always